'use client';

import React, { useState, useRef } from 'react';
import { motion } from 'framer-motion';
import { UploadCloud, FileImage, Loader2, CreditCard } from 'lucide-react';
import { LocalImage } from '@/lib/types';

export default function Home() {
  const [images, setImages] = useState<LocalImage[]>([]);
  const [isProcessingFiles, setIsProcessingFiles] = useState(false);
  const [isRedirecting, setIsRedirecting] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const generatePreview = async (file: File): Promise<{ previewUrl: string; isUnsupported?: boolean }> => {
    const ext = file.name.substring(file.name.lastIndexOf('.')).toLowerCase();

    // Convert HEIC/HEIF on the fly using heic2any
    if (ext === '.heic' || ext === '.heif') {
      try {
        const heic2any = (await import('heic2any')).default;
        const convertedBlob = await heic2any({ blob: file, toType: 'image/jpeg', quality: 0.5 });
        const blobArray = Array.isArray(convertedBlob) ? convertedBlob : [convertedBlob];
        return { previewUrl: URL.createObjectURL(blobArray[0]) };
      } catch (e) {
        console.error('Error converting HEIC:', e);
        return { previewUrl: '', isUnsupported: true };
      }
    }

    // For unsupported browser native formats
    if (ext === '.tiff' || ext === '.bmp' || ext === '.avif') {
      return { previewUrl: '', isUnsupported: true };
    }

    return { previewUrl: URL.createObjectURL(file) };
  };

  const handleFiles = async (e: React.ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    if (!e.target.files || e.target.files.length === 0) return;

    setIsProcessingFiles(true);
    const files = Array.from(e.target.files);

    const MAX_SIZE = 50 * 1024 * 1024; // 50MB
    const validExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.heic', '.heif', '.avif', '.tiff', '.bmp'];

    const validFiles = files.filter(file => {
      const ext = file.name.substring(file.name.lastIndexOf('.')).toLowerCase();
      return file.size <= MAX_SIZE && validExtensions.includes(ext);
    });

    try {
      const processedImages = await Promise.all(
        validFiles.map(async (file) => {
          const { previewUrl, isUnsupported } = await generatePreview(file);
          return {
            id: crypto.randomUUID(),
            file,
            previewUrl,
            isUnsupportedBrowserFormat: isUnsupported,
          };
        })
      );

      setImages(prev => [...prev, ...processedImages]);

      // We would normally upload these files to our cloud storage here or via pre-signed URLs
      // For this MVP, we hold them in local state and upload them in the background
      // or right before checkout. For now, they are ready to be previewed.

    } catch (err) {
      console.error("Error processing files", err);
    } finally {
      setIsProcessingFiles(false);
      if (fileInputRef.current) {
        fileInputRef.current.value = ''; // reset input
      }
    }
  };

  const handleCheckout = async () => {
    if (images.length === 0) return;

    setIsRedirecting(true);

    try {
      // Create a unique Job ID for this order
      const jobId = `job_${crypto.randomUUID().substring(0, 12)}`;

      // Note: In a fully wired production environment, we would first ensure all `images`
      // are uploaded to our Vercel Blob/AWS bucket and mapped to this `jobId`
      // BEFORE redirecting to Stripe.

      // Since generation happens AFTER checkout now, we don't call /api/style here.
      // We go straight to checkout.
      const res = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          jobId,
          // We pass a dummy zip URL because the real one will be generated by the webhook
          // after payment triggers the Python engine.
          zipUrl: `http://localhost:8000/download/${jobId}_mosaic_kit.zip`
        }),
      });

      const data = await res.json();
      if (data.url) {
        window.location.href = data.url;
      } else {
        throw new Error("No checkout URL returned");
      }
    } catch (e) {
      console.error('Checkout error:', e);
      setIsRedirecting(false);
      alert('Es gab ein Problem bei der Weiterleitung zu Stripe. Bitte versuche es erneut.');
    }
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-full w-full max-w-4xl py-12 px-4 sm:px-6">

      {/* Hero Section */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-12 space-y-4"
      >
        <h1 className="text-5xl sm:text-6xl font-bold tracking-tight">
          Dein Persönliches Fotomosaik
        </h1>
        <p className="text-xl text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
          Lade dein Hauptmotiv und bis zu 30 Kacheln hoch. Unsere KI generiert dein Mosaik und das druckfertige Schnittmuster.
        </p>
      </motion.div>

      {/* Upload Zone */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.1 }}
        className="w-full flex flex-col items-center bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-3xl p-8 mb-12"
      >
        <UploadCloud className="w-16 h-16 text-gray-400 mb-6" />

        <label className={`cursor-pointer px-8 py-4 rounded-full text-xl font-medium transition-all hover:shadow-lg flex items-center gap-3 ${
          isProcessingFiles
            ? 'bg-gray-200 text-gray-500 cursor-wait'
            : 'bg-black text-white dark:bg-white dark:text-black'
        }`}>
          {isProcessingFiles ? (
            <>
              <Loader2 className="w-6 h-6 animate-spin" />
              Verarbeite Bilder...
            </>
          ) : (
            <>
              <span>+ Bilder auswählen</span>
            </>
          )}
          <input
            ref={fileInputRef}
            type="file"
            className="hidden"
            multiple
            accept=".jpg,.jpeg,.png,.webp,.heic,.heif,.avif,.tiff,.bmp"
            onChange={handleFiles}
            disabled={isProcessingFiles}
          />
        </label>
        <p className="mt-4 text-sm text-gray-500 text-center max-w-[300px]">
          Wähle dein Hauptbild und die Kacheln in einem Rutsch aus. Max 50MB pro Bild.
        </p>
      </motion.div>

      {/* Image Preview Grid */}
      {images.length > 0 && (
        <div className="w-full mb-12">
          <div className="flex justify-between items-end mb-4">
            <h3 className="text-xl font-medium">Ausgewählte Bilder ({images.length})</h3>
            <button
              onClick={() => setImages([])}
              className="text-sm text-red-500 hover:underline"
            >
              Alle löschen
            </button>
          </div>
          <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 gap-3 max-h-[300px] overflow-y-auto p-2 bg-gray-50 dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800">
            {images.map((img) => (
              <div key={img.id} className="relative aspect-square rounded-lg overflow-hidden border border-gray-200 dark:border-gray-700 bg-white dark:bg-black">
                {img.isUnsupportedBrowserFormat ? (
                  <div className="w-full h-full flex items-center justify-center">
                    <FileImage className="w-8 h-8 text-gray-400" />
                  </div>
                ) : (
                  /* eslint-disable-next-line @next/next/no-img-element */
                  <img src={img.previewUrl} alt="Thumbnail" className="w-full h-full object-cover" />
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Checkout Button */}
      <motion.button
        disabled={images.length === 0 || isRedirecting}
        onClick={handleCheckout}
        whileHover={images.length > 0 && !isRedirecting ? { scale: 1.05 } : {}}
        whileTap={images.length > 0 && !isRedirecting ? { scale: 0.95 } : {}}
        className={`w-full max-w-md px-8 py-5 rounded-full text-xl font-semibold transition-all flex items-center justify-center gap-3 ${
          images.length > 0 && !isRedirecting
            ? 'bg-blue-600 hover:bg-blue-700 text-white shadow-lg shadow-blue-600/30'
            : 'bg-gray-200 text-gray-400 dark:bg-gray-800 dark:text-gray-600 cursor-not-allowed'
        }`}
      >
        {isRedirecting ? (
          <>
            <Loader2 className="w-6 h-6 animate-spin" />
            Weiterleiten...
          </>
        ) : (
          <>
            <CreditCard className="w-6 h-6" />
            Sicher bezahlen mit Stripe
          </>
        )}
      </motion.button>
      <p className="mt-4 text-sm text-gray-500 text-center">
        Die KI-Generierung startet automatisch direkt nach dem sicheren Checkout.
      </p>

    </div>
  );
}
